[package]
name = "okno-app"
description = "Okno desktop application"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "okno"
path = "src/main.rs"

[dependencies]
okno-proto.workspace = true
okno-net.workspace = true
okno-auth.workspace = true
okno-discovery.workspace = true
okno-desktop.workspace = true
okno-core.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
sys-locale = "0.3"
arboard = "3"
dirs.workspace = true
if-addrs.workspace = true
vt100 = "0.16"
slint = { version = "1.18", features = ["unstable-winit-030"] }

futures-util = "0.3"

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { version = "0.13", default-features = false, features = ["async-io", "settings", "file_chooser"] }

[target.'cfg(windows)'.dependencies]
rfd = { version = "0.15", default-features = false }

[build-dependencies]
slint-build = "1.18"
